<?php

//redirecionamento do login
//function cadastros_user_login(&$edit, $account) {
/*function teste_user_login(&$edit, $account) {
	$edit['redirect'] = 'juridico';
}
*/

/**
  * Implements hook_permission().
  * Definições das permissões de uso e acesso ao módulo
  */
//function cadastros_permission() {

function teste_permission() {
	return array(
		'Liberar cadastros' => array(
		'title' => t('Access module cadastros'),
		'description' => t('Administração e acesso ao módulo.'),
		),
	);
}

/**
 * TO DO LIST
 * - CLIENTES => 	- validações
 * 					
 * - PROCESSOS =>	- VALIDAÇÕES
 * 					- POPUP
 * 					- ATUALIZAÇÕES
 * 					- TROCA DE CLIENTES E DE PROCESSOS VIA JAVASCRIPT
 * 
 * 	- LISTAGENS =>	- VIEWS
 */
 
/**
  * Implements hook_menu().
  */
  
function teste_menu()
{
	$items = array();
/*	
	$items['juridico'] = array(
		'title' => 'Sistema Jurídico',
		'description' => 'Cadastro de processos',
//		'page callback' => 'drupal_get_form',
//		'page arguments' => array('juridico'),
//		'access arguments' => array('Liberar cadastros'),
		'page callback' => '_juridico', //funcao que irá chamar o formulario
		'access arguments' => array('access content') ,		
		'type' => MENU_CALLBACK,
	);
*/
	//cadastro de cliente
	$items['juridico/cadastro/cliente'] = array(
		'title' => 'Cadastro de Cliente',
		'description' => 'Cadastre aqui o cliente',
		'page callback' => '_cadastro_cliente', //funcao que irá chamar o formulario
		'access arguments' => array('access content') ,		
		'type' => MENU_NORMAL_ITEM,
	);
	
	//cadastro de ação	
	$items['juridico/cadastro/acao'] = array(
		'title' => 'Cadastro de Tipo de Ação',
		'description' => 'Cadastre aqui as os tipos de ação',
		'page callback' => '_cadastro_acao', //funcao que irá chamar o formulario
		'access arguments' => array('access content') ,		
		'type' => MENU_NORMAL_ITEM,
		//'file' => 'cadastros.inc',
	);

	//cadastro de varas
	$items['juridico/cadastro/varas'] = array(
		'title' => 'Cadastro de Varas',
		'description' => 'Cadastre aqui as varas judiciais',
		'page callback' => '_cadastro_varas', //funcao que irá chamar o formulario
		'access arguments' => array('access content') ,		
		'type' => MENU_NORMAL_ITEM,
	);
/*	
    $items['meu-formulario'] = array(
		'title' => 'Meu formulario' ,
		'description' => t('Meu Primeiro Formulario') ,
		'page callback' => '_meu_formulario', //funcao que irá chamar o formulario
		'access arguments' => array('access content') ,
		//'type' => MENU_CALLBACK,
		'type' => MENU_NORMAL_ITEM,
	);
*/  
		//cadastro de comarcas
	$items['juridico/cadastro/comarcas'] = array(
		'title' => 'Cadastro de Comarcas',
		'description' => 'Cadastre aqui as comarcas',
		'page callback' => '_cadastro_comarcas', //funcao que irá chamar o formulario
		'access arguments' => array('access content') ,		
		'type' => MENU_NORMAL_ITEM,
	);
	
	//cadastro de natureza
	$items['juridico/cadastro/naturezas'] = array(
		'title' => 'Cadastro de Natureza',
		'description' => 'Cadastre aqui a natureza do processo',
		'page callback' => '_cadastro_natureza', //funcao que irá chamar o formulario
		'access arguments' => array('access content') ,		
		'type' => MENU_NORMAL_ITEM,
	);
	
	
	//cadastro de tribunais
	$items['juridico/cadastro/tribunais'] = array(
		'title' => 'Cadastro do Tribunal',
		'description' => 'Cadastre aqui os tribunais',
		'page callback' => '_cadastro_tribunais', //funcao que irá chamar o formulario
		'access arguments' => array('access content') ,		
		'type' => MENU_NORMAL_ITEM,
	);

	
	//cadastro de conta
	$items['juridico/cadastro/conta'] = array(
		'title' => 'Cadastro de Tipo de Conta',
		'description' => 'Cadastre aqui os tipos de conta',
		'page callback' => '_cadastro_conta', //funcao que irá chamar o formulario
		'access arguments' => array('access content') ,		
		'type' => MENU_NORMAL_ITEM,
	);

	//cadastro de fase processual
	$items['juridico/cadastro/fase_processual'] = array(
		'title' => 'Cadastro de Fase Processual',
		'description' => 'Cadastre aqui as Fases Processuais',
		'page callback' => '_cadastro_fase_processual', //funcao que irá chamar o formulario
		'access arguments' => array('access content') ,		
		'type' => MENU_NORMAL_ITEM,
	);

	//cadastro de regional/sucursal
	$items['juridico/cadastro/regional'] = array(
		'title' => 'Cadastro de Regional/Sucursal',
		'description' => 'Cadastre aqui a Regional/Sucursal',
		'page callback' => '_cadastro_regional', //funcao que irá chamar o formulario
		'access arguments' => array('access content') ,		
		'type' => MENU_NORMAL_ITEM,
	);

	//cadastro de Recursos(tribunais)
	$items['juridico/cadastro/recursos'] = array(
		'title' => 'Cadastro de Recursos',
		'description' => 'Cadastre aqui o Recurso(tribunal)',
		'page callback' => '_cadastro_recurso', //funcao que irá chamar o formulario
		'access arguments' => array('access content') ,		
		'type' => MENU_NORMAL_ITEM,
	);

	//cadastro de Possibilidade de exito
	$items['juridico/cadastro/exito'] = array(
		'title' => 'Cadastro de Possibilidade de Êxito',
		'description' => 'Cadastre aqui a possibilidade de êxito',
		'page callback' => '_cadastro_exito', //funcao que irá chamar o formulario
		'access arguments' => array('access content') ,		
		'type' => MENU_NORMAL_ITEM,
	);
  

  return $items;  
  
  
} 
/*
function _juridico()
{
  $output = drupal_get_form('juridico_page'); 
  return $output;
}

function juridico() {
	$form = array();
	//redirecionar pro node de escolha de processos
	//$act = renderiza_cadastro(9);
	return $form;
	//global $attributes_array;
	//drupal_set_message(dpr($page),'status');
	//print render($page['processos']);

}
*/

function _meu_formulario()
{
  $output = drupal_get_form('estrutura_do_formulario'); 
  return $output;
}

function _cadastro_acao()
{
  $output = drupal_get_form('form_acao'); 
  return $output;
}

function _cadastro_varas()
{
  $output = drupal_get_form('form_varas'); 
  return $output;
}

function _cadastro_comarcas()
{
  $output = drupal_get_form('form_comarcas'); 
  return $output;
}

function _cadastro_natureza()
{
  $output = drupal_get_form('form_natureza'); 
  return $output;
}

function _cadastro_tribunais()
{
  $output = drupal_get_form('form_tribunais'); 
  return $output;
}
function _cadastro_conta() {
  $output = drupal_get_form('form_conta'); 
  return $output;
}

function _cadastro_fase_processual() {
  $output = drupal_get_form('form_fase_processual'); 
  return $output;
}

function _cadastro_regional() {
  $output = drupal_get_form('form_regional'); 
  return $output;
}

function _cadastro_exito() {
  $output = drupal_get_form('form_exito'); 
  return $output;
}

function _cadastro_recurso() {
  $output = drupal_get_form('form_recursos'); 
  return $output;
}

function _cadastro_cliente() {
  $output = drupal_get_form('form_cliente'); 
  return $output;
}

function form_conta() {
	$form = array();
	
	$form['nome'] = array(
		'#type' => 'textfield',
		'#title' => 'Nome da Conta',
		'#required' => true,
	);
	
//	$form['#submit'][] = '_cadastros_vara_settings_submit';
	$breadcrumb = array();
	$breadcrumb[] = l('Home',base_path());
	$breadcrumb[] = l('Juridico','juridico');
	//$breadcrumb[] = l('Processos',base_path().'processos');
	//$breadcrumb[] = l(drupal_get_title(),base_path() . request_uri());	
	//$breadcrumb[] = l('Processo Corrente','processos/processo_corrente');
	drupal_set_breadcrumb($breadcrumb);

    $form['submit'] = array('#type' => 'submit', '#value' => t('Enviar'), '#weight' => 1,
               '#ajax' => array(
                'callback' => 'form_conta_submit_callback', //Função do Submit
                'wrapper' => 'codigo-ajax', //Id onde será exibido a Mensagem.
                'effect' => 'fade',),);
 
 $form['body']['#prefix'] = '<div id="codigo-ajax">'; //Div onde será exibida a Mensagem
 $form['body']['#suffix'] = '</div>';
 
 return $form;
}

function form_fase_processual() {
	$form = array();
	
	$form['nome'] = array(
		'#type' => 'textfield',
		'#title' => 'Nome da Fase Processual',
		'#required' => true,
	);
	
//	$form['#submit'][] = '_cadastros_vara_settings_submit';
	$breadcrumb = array();
	$breadcrumb[] = l('Home',base_path());
	$breadcrumb[] = l('Juridico','juridico');
	//$breadcrumb[] = l('Processos',base_path().'processos');
	//$breadcrumb[] = l(drupal_get_title(),base_path() . request_uri());	
	//$breadcrumb[] = l('Processo Corrente','processos/processo_corrente');
	drupal_set_breadcrumb($breadcrumb);

    $form['submit'] = array('#type' => 'submit', '#value' => t('Enviar'), '#weight' => 1,
               '#ajax' => array(
                'callback' => 'form_fase_submit_callback', //Função do Submit
                'wrapper' => 'codigo-ajax', //Id onde será exibido a Mensagem.
                'effect' => 'fade',),);
 
 $form['body']['#prefix'] = '<div id="codigo-ajax">'; //Div onde será exibida a Mensagem
 $form['body']['#suffix'] = '</div>';
 
 return $form;
}


function form_cliente() {
	$form = array();

	//******Tipo de cliente
	//Geral - cliente - adverso - advogado adverso - advogado cliente
	$form['tipo'] = array(
		'#type' => 'checkboxes',
		'#options' => array(0 => 'Geral', 1 => 'Cliente', 2 => 'Adverso', 3 => 'Advogado Adverso', 4 => 'Advogado Cliente'),
		'#title' => 'Tipo de cadastro',
	);
	
	$form['pessoa_tipo'] = array(
		'#type' => 'radios',
		'#default_value' => 0,
		'#options' => array(0 => 'Pessoa Física', 1 => 'Pessoa Jurídica'),
		'#title' => 'Pessoa',
	);
		
	$form['observacao'] = array(
		'#type' => 'textarea',
		'#title' => 'Observações',
	);
	//******PRINCIPAL
	//Nascimento
	//RG - orgao expedidor
	//Data exp
	//CPF
	//nacionalidade
	//profissão - estado civil
	//definição do fieldset
	$form['principal'] = array(
		'#type' => 'fieldset',
		'#title' => 'PRINCIPAL',
		'#collapsible' => TRUE,
		'#collapsed' => FALSE,
	);

	$form['principal']['nome'] = array(
		'#type' => 'textfield',
		'#title' => 'Nome do Cliente',
		'#required' => true
	);
	
	$form['principal']['data_nasc'] = array(
		'#type' => 'date',
		'#title' => 'Nascimento',
		'#required' => true
	);

		
	//RG varia de estado para estado
	$form['principal']['RG'] = array(
		'#type' => 'textfield',
		'#title' => 'RG',
		'#required' => true
	);
	
	$form['principal']['org_exp'] = array(
		'#type' => 'textfield',
		'#title' => 'Órgão Expedidor',
		'#required' => true
	);

	$form['principal']['data_exp'] = array(
		'#type' => 'date',
		'#title' => 'Data expedição',
		'#required' => true
	);
	
	$form['principal']['CPF'] = array(
		'#type' => 'textfield',
		'#title' => 'CPF',
		'#required' => true
	);

	$form['principal']['nacionalidade'] = array(
		'#type' => 'textfield',
		'#title' => 'Nacionalidade',
		'#required' => true
	);

	$form['principal']['profissao'] = array(
		'#type' => 'textfield',
		'#title' => 'Profissão',
		'#required' => true
	);

	$form['principal']['estado_civil'] = array(
       '#type' => 'select',
       '#title' => t('Estado Civil'),
       '#options' => array(
			0 => t('Solteiro'),
			1 => t('Casado'),
			2 => t('Divorciado'),
			3 => t('Viúvo'),
			4 => t('União Estável'),			
		),
       '#default_value' => 0,
       //'#description' => t('Selecione o Estado Civil'),
   );

	//*******OUTROS
	//PIS
	//Numero da CT - Série
	$form['outros'] = array(
		'#type' => 'fieldset',
		'#title' => 'OUTROS',
		'#collapsible' => TRUE,
		'#collapsed' => TRUE,
	);
		
	$form['outros']['PIS'] = array(
		'#type' => 'textfield',
		'#title' => 'Profissão',
		'#required' => false
	);	
	/*
	$form['outros']['PIS'] = array(
		popup(array('view' => 'frontpage', 'activate' => 'click', 'width' => 500)),
	);

	$form['outros']['PIS'] = array(
		'#type' => 'textfield',
		'#title' => 	popup(array('view' => 'frontpage', 'activate' => 'click', 'width' => 500)),
		'#required' => false
	);
	*/
	$form['outros']['num_ct'] = array(
		'#type' => 'textfield',
		'#title' => 'Número da CT',
		'#required' => false
	);	
	
	$form['outros']['serie'] = array(
		'#type' => 'textfield',
		'#title' => 'Série',
		'#required' => false
	);	
	
	//*******RESIDENCIAL
	//Endereço - CEP
	//estado - cidade - bairro
	//telefone - contato
	//email
	$form['residencial'] = array(
		'#type' => 'fieldset',
		'#title' => 'RESIDENCIAL',
		'#collapsible' => TRUE,
		'#collapsed' => TRUE,
	);
	
	$form['residencial']['res_endereco'] = array(
		'#type' => 'textfield',
		'#title' => 'Endereço',
		'#required' => true
	);	

	$form['residencial']['res_CEP'] = array(
		'#type' => 'textfield',
		'#title' => 'CEP',
		'#required' => false
	);	
	
	$form['residencial']['res_estado'] = array(
		'#type' => 'select',
		'#title' => 'UF',
		'#options' => array(
			'AC' => 'AC',
			'AL' => 'AL',
			'AP' => 'AP',
			'AM' => 'AM',
			'BA' => 'BA',
			'CE' => 'CE',
			'DF' => 'DF',
			'ES' => 'ES',
			'GO' => 'GO',
			'MA' => 'MA',
			'MT' => 'MT',
			'MS' => 'MS',
			'MG' => 'MG',
			'PA' => 'PA',
			'PB' => 'PB',
			'PR' => 'PR',
			'PE' => 'PE',
			'PI' => 'PI',
			'RJ' => 'RJ',
			'RN' => 'RN',
			'RS' => 'RS',
			'RO' => 'RO',
			'RR' => 'RR',
			'SC' => 'SC',
			'SP' => 'SP',
			'SE' => 'SE',
			'TO' => 'TO',
		),
		'#required' => true,
		'#default_value' => 'RS',
	);	
	
	$form['residencial']['res_cidade'] = array(
		'#type' => 'textfield',
		'#title' => 'Cidade',
		'#required' => false
	);	

	$form['residencial']['res_telefone'] = array(
		'#type' => 'textfield',
		'#title' => 'Telefone',
		'#required' => false
	);	
	
	$form['residencial']['res_celular'] = array(
		'#type' => 'textfield',
		'#title' => 'Contato',
		'#required' => false
	);	
	
	$form['residencial']['res_email'] = array(
		'#type' => 'textfield',
		'#title' => 'Email',
		'#required' => false
	);	
	
	//*******COMERCIAL
	//Endereço - CEP
	//estado - cidade - bairro
	//telefone - contato
	//email
	$form['comercial'] = array(
		'#type' => 'fieldset',
		'#title' => 'COMERCIAL',
		'#collapsible' => TRUE,
		'#collapsed' => TRUE,
	);

	$form['comercial']['com_endereco'] = array(
		'#type' => 'textfield',
		'#title' => 'Endereço',
		'#required' => false
	);	

	$form['comercial']['com_CEP'] = array(
		'#type' => 'textfield',
		'#title' => 'CEP',
		'#required' => false
	);	
	
	$form['comercial']['com_estado'] = array(
		'#type' => 'select',
		'#title' => 'UF',
		'#options' => array(
			'AC' => 'AC',
			'AL' => 'AL',
			'AP' => 'AP',
			'AM' => 'AM',
			'BA' => 'BA',
			'CE' => 'CE',
			'DF' => 'DF',
			'ES' => 'ES',
			'GO' => 'GO',
			'MA' => 'MA',
			'MT' => 'MT',
			'MS' => 'MS',
			'MG' => 'MG',
			'PA' => 'PA',
			'PB' => 'PB',
			'PR' => 'PR',
			'PE' => 'PE',
			'PI' => 'PI',
			'RJ' => 'RJ',
			'RN' => 'RN',
			'RS' => 'RS',
			'RO' => 'RO',
			'RR' => 'RR',
			'SC' => 'SC',
			'SP' => 'SP',
			'SE' => 'SE',
			'TO' => 'TO',
		),
		'#required' => true,
		'#default_value' => 'RS',
	);	
	
	$form['comercial']['com_cidade'] = array(
		'#type' => 'textfield',
		'#title' => 'Cidade',
		'#required' => false
	);	

	$form['comercial']['com_telefone'] = array(
		'#type' => 'textfield',
		'#title' => 'Telefone',
		'#required' => false
	);	
	
	$form['comercial']['com_celular'] = array(
		'#type' => 'textfield',
		'#title' => 'Contato',
		'#required' => false
	);	
	
	$form['comercial']['com_email'] = array(
		'#type' => 'textfield',
		'#title' => 'Email',
		'#required' => false
	);
/*	
	$form['enviar'] = array(
		'#type' => 'submit',
		'#value' => 'Enviar',
		'#required' => true
	);
	
	$form['#submit'][] = '_cadastros_client_settings_submit';
*/
	$breadcrumb = array();
	$breadcrumb[] = l('Home',base_path());
	$breadcrumb[] = l('Juridico','juridico');
	//$breadcrumb[] = l('Processos',base_path().'processos');
	//$breadcrumb[] = l(drupal_get_title(),base_path() . request_uri());	
	//$breadcrumb[] = l('Processo Corrente','processos/processo_corrente');
	drupal_set_breadcrumb($breadcrumb);


    $form['submit'] = array('#type' => 'submit', '#value' => t('Enviar'), '#weight' => 1,
               '#ajax' => array(
                'callback' => 'form_cliente_submit_callback', //Função do Submit
                'wrapper' => 'codigo-ajax', //Id onde será exibido a Mensagem.
                'effect' => 'fade',),);
 
 $form['body']['#prefix'] = '<div id="codigo-ajax">'; //Div onde será exibida a Mensagem
 $form['body']['#suffix'] = '</div>';

	return $form;
}




function form_regional() {
	$form = array();
	
	$form['nome'] = array(
		'#type' => 'textfield',
		'#title' => 'Nome da Regional/Sucursal',
		'#required' => true,
	);
	
//	$form['#submit'][] = '_cadastros_vara_settings_submit';
	$breadcrumb = array();
	$breadcrumb[] = l('Home',base_path());
	$breadcrumb[] = l('Juridico','juridico');
	//$breadcrumb[] = l('Processos',base_path().'processos');
	//$breadcrumb[] = l(drupal_get_title(),base_path() . request_uri());	
	//$breadcrumb[] = l('Processo Corrente','processos/processo_corrente');
	drupal_set_breadcrumb($breadcrumb);

    $form['submit'] = array('#type' => 'submit', '#value' => t('Enviar'), '#weight' => 1,
               '#ajax' => array(
                'callback' => 'form_regional_submit_callback', //Função do Submit
                'wrapper' => 'codigo-ajax', //Id onde será exibido a Mensagem.
                'effect' => 'fade',),);
 
 $form['body']['#prefix'] = '<div id="codigo-ajax">'; //Div onde será exibida a Mensagem
 $form['body']['#suffix'] = '</div>';
 
 return $form;
}

function form_exito() {
	$form = array();
	
	$form['nome'] = array(
		'#type' => 'textfield',
		'#title' => 'Nome da Possibilidade de êxito',
		'#required' => true,
	);
	
//	$form['#submit'][] = '_cadastros_vara_settings_submit';
	$breadcrumb = array();
	$breadcrumb[] = l('Home',base_path());
	$breadcrumb[] = l('Juridico','juridico');
	//$breadcrumb[] = l('Processos',base_path().'processos');
	//$breadcrumb[] = l(drupal_get_title(),base_path() . request_uri());	
	//$breadcrumb[] = l('Processo Corrente','processos/processo_corrente');
	drupal_set_breadcrumb($breadcrumb);

    $form['submit'] = array('#type' => 'submit', '#value' => t('Enviar'), '#weight' => 1,
               '#ajax' => array(
                'callback' => 'form_exito_submit_callback', //Função do Submit
                'wrapper' => 'codigo-ajax', //Id onde será exibido a Mensagem.
                'effect' => 'fade',),);
 
 $form['body']['#prefix'] = '<div id="codigo-ajax">'; //Div onde será exibida a Mensagem
 $form['body']['#suffix'] = '</div>';
 
 return $form;
}

function form_recursos() {
	$form = array();
	
	$form['nome'] = array(
		'#type' => 'textfield',
		'#title' => 'Nome do Recurso',
		'#required' => true,
	);
	
//	$form['#submit'][] = '_cadastros_vara_settings_submit';
	$breadcrumb = array();
	$breadcrumb[] = l('Home',base_path());
	$breadcrumb[] = l('Juridico','juridico');
	//$breadcrumb[] = l('Processos',base_path().'processos');
	//$breadcrumb[] = l(drupal_get_title(),base_path() . request_uri());	
	//$breadcrumb[] = l('Processo Corrente','processos/processo_corrente');
	drupal_set_breadcrumb($breadcrumb);

    $form['submit'] = array('#type' => 'submit', '#value' => t('Enviar'), '#weight' => 1,
               '#ajax' => array(
                'callback' => 'form_recursos_submit_callback', //Função do Submit
                'wrapper' => 'codigo-ajax', //Id onde será exibido a Mensagem.
                'effect' => 'fade',),);
 
 $form['body']['#prefix'] = '<div id="codigo-ajax">'; //Div onde será exibida a Mensagem
 $form['body']['#suffix'] = '</div>';
 
 return $form;
}


function form_comarcas() {
	$form = array();
	
	$form['nome'] = array(
		'#type' => 'textfield',
		'#title' => 'Nome da Comarca',
		'#required' => true,
	);
	
//	$form['#submit'][] = '_cadastros_vara_settings_submit';
	$breadcrumb = array();
	$breadcrumb[] = l('Home',base_path());
	$breadcrumb[] = l('Juridico','juridico');
	//$breadcrumb[] = l('Processos',base_path().'processos');
	//$breadcrumb[] = l(drupal_get_title(),base_path() . request_uri());	
	//$breadcrumb[] = l('Processo Corrente','processos/processo_corrente');
	drupal_set_breadcrumb($breadcrumb);

    $form['submit'] = array('#type' => 'submit', '#value' => t('Enviar'), '#weight' => 1,
               '#ajax' => array(
                'callback' => 'form_comarca_submit_callback', //Função do Submit
                'wrapper' => 'codigo-ajax', //Id onde será exibido a Mensagem.
                'effect' => 'fade',),);
 
 $form['body']['#prefix'] = '<div id="codigo-ajax">'; //Div onde será exibida a Mensagem
 $form['body']['#suffix'] = '</div>';
 
 return $form;
}

function form_natureza() {
	$form = array();
	
	$form['nome'] = array(
		'#type' => 'textfield',
		'#title' => 'Nome da Natureza',
		'#required' => true,
	);
	
//	$form['#submit'][] = '_cadastros_vara_settings_submit';
	$breadcrumb = array();
	$breadcrumb[] = l('Home',base_path());
	$breadcrumb[] = l('Juridico','juridico');
	//$breadcrumb[] = l('Processos',base_path().'processos');
	//$breadcrumb[] = l(drupal_get_title(),base_path() . request_uri());	
	//$breadcrumb[] = l('Processo Corrente','processos/processo_corrente');
	drupal_set_breadcrumb($breadcrumb);

    $form['submit'] = array('#type' => 'submit', '#value' => t('Enviar'), '#weight' => 1,
               '#ajax' => array(
                'callback' => 'form_natureza_submit_callback', //Função do Submit
                'wrapper' => 'codigo-ajax', //Id onde será exibido a Mensagem.
                'effect' => 'fade',),);
 
 $form['body']['#prefix'] = '<div id="codigo-ajax">'; //Div onde será exibida a Mensagem
 $form['body']['#suffix'] = '</div>';
 
 return $form;
}

function form_tribunais() {
	$form = array();
	
	$form['nome'] = array(
		'#type' => 'textfield',
		'#title' => 'Nome do Tribunal',
		'#required' => true,
	);
	
//	$form['#submit'][] = '_cadastros_vara_settings_submit';
	$breadcrumb = array();
	$breadcrumb[] = l('Home',base_path());
	$breadcrumb[] = l('Juridico','juridico');
	//$breadcrumb[] = l('Processos',base_path().'processos');
	//$breadcrumb[] = l(drupal_get_title(),base_path() . request_uri());	
	//$breadcrumb[] = l('Processo Corrente','processos/processo_corrente');
	drupal_set_breadcrumb($breadcrumb);

    $form['submit'] = array('#type' => 'submit', '#value' => t('Enviar'), '#weight' => 1,
               '#ajax' => array(
                'callback' => 'form_tribunais_submit_callback', //Função do Submit
                'wrapper' => 'codigo-ajax', //Id onde será exibido a Mensagem.
                'effect' => 'fade',),);
 
 $form['body']['#prefix'] = '<div id="codigo-ajax">'; //Div onde será exibida a Mensagem
 $form['body']['#suffix'] = '</div>';
 
 return $form;
}

function form_acao() {
//	module_load_include('inc', 'popup', '/includes/popup.api');
	$form = array();
	
	$form['nome'] = array(
		'#type' => 'textfield',
		'#title' => 'Nome do Tipo de Ação',
		'#required' => true
	);
	
	//$form['#submit'][] = '_cadastros_acao_settings_submit';
	
	$breadcrumb = array();
	$breadcrumb[] = l('Home',base_path());
	$breadcrumb[] = l('Juridico','juridico');
	//$breadcrumb[] = l('Processos',base_path().'processos');
	//$breadcrumb[] = l(drupal_get_title(),base_path() . request_uri());	
	//$breadcrumb[] = l('Processo Corrente','processos/processo_corrente');
	drupal_set_breadcrumb($breadcrumb);
	
    $form['submit'] = array('#type' => 'submit', '#value' => t('Enviar'), '#weight' => 1,
               '#ajax' => array(
                'callback' => 'form_acao_submit_callback', //Função do Submit
                'wrapper' => 'codigo-ajax', //Id onde será exibido a Mensagem.
                'effect' => 'fade',),);
 
 $form['body']['#prefix'] = '<div id="codigo-ajax">'; //Div onde será exibida a Mensagem
 $form['body']['#suffix'] = '</div>';
 
 return $form;
}


function form_varas() {
//	module_load_include('inc', 'popup', '/includes/popup.api');
	$form = array();
	
	$form['nome'] = array(
		'#type' => 'textfield',
		'#title' => 'Nome da Vara',
		'#required' => true,
	);
	
//	$form['#submit'][] = '_cadastros_vara_settings_submit';
	$breadcrumb = array();
	$breadcrumb[] = l('Home',base_path());
	$breadcrumb[] = l('Juridico','juridico');
	//$breadcrumb[] = l('Processos',base_path().'processos');
	//$breadcrumb[] = l(drupal_get_title(),base_path() . request_uri());	
	//$breadcrumb[] = l('Processo Corrente','processos/processo_corrente');
	drupal_set_breadcrumb($breadcrumb);

    $form['submit'] = array('#type' => 'submit', '#value' => t('Enviar'), '#weight' => 1,
               '#ajax' => array(
                'callback' => 'form_varas_submit_callback', //Função do Submit
                'wrapper' => 'codigo-ajax', //Id onde será exibido a Mensagem.
                'effect' => 'fade',),);
 
 $form['body']['#prefix'] = '<div id="codigo-ajax">'; //Div onde será exibida a Mensagem
 $form['body']['#suffix'] = '</div>';
 
 return $form;
}


function estrutura_do_formulario(){
  module_load_include('inc', 'popup', '/includes/popup.api');
  /*
  $form['description'] = array(
    '#type' => 'item',
    '#title' => t('Meu Formulario'),
  );
 
  $form['campo_checkbox'] = array(
      '#title' => t('Meu campo'),
      '#type' => 'checkbox',
      '#return_value' => 1, 
      '#default_value' => 1,
  );
 */
  $form['nome'] = array(
      '#title' => t('Outro campo:'),
      '#type' => 'textfield',
      //'#field_suffix' => l('px'),
      //'#field_suffix' => popup(array('form' => 'search_form', 'activate' => 'click', 'width' => 350)),
      '#field_suffix' => popup(array('form' => 'search_form', 'activate' => 'click','close' => TRUE, 'width' => 450)),
  );
 
 
  $form['submit'] = array('#type' => 'submit', '#value' => t('Submit'), '#weight' => 1,
               '#ajax' => array(
                'callback' => 'meu_form_submit_callback', //Função do Submit
                'wrapper' => 'codigo-ajax', //Id onde será exibido a Mensagem.
                'effect' => 'fade',),);
 
 $form['body']['#prefix'] = '<div id="codigo-ajax">'; //Div onde será exibida a Mensagem
 $form['body']['#suffix'] = '</div>';
 
 return $form;
}
 
 
 
//Funções de Submit Ajax

//cliente
function form_cliente_submit_callback($form, &$form_state) {
/********************************/
/*
  	$table = 'cadastros_cliente';
	
	$record = array(
		'nome' => $form_state['values']['nome'],
	);
*/
/**********************************/

	$table = 'cadastros_clientes';
	$mes = $form_state['values']['data_nasc']['month'];
	$dia = $form_state['values']['data_nasc']['day'];
	$ano = $form_state['values']['data_nasc']['year'];
	$data_set = $ano.'/'.$mes.'/'.$dia;
	$date_conversor_nasc = strtotime($data_set);

	$mes = $form_state['values']['data_exp']['month'];
	$dia = $form_state['values']['data_exp']['day'];
	$ano = $form_state['values']['data_exp']['year'];
	$data_set = $ano.'/'.$mes.'/'.$dia;
	$date_conversor_exp = strtotime($data_set);


	//drupal_set_message(print_r($date_conversor_nasc,1),'warning');
	//drupal_set_message(print_r($date_conversor_exp,1),'warning');
	$record = array(
		'nome' => $form_state['values']['nome'],
		'data_nasc'=> $date_conversor_nasc,
		'RG' => $form_state['values']['RG'],
		'org_exp' => $form_state['values']['org_exp'],
		//'data_exp' => $form_state['values']['data_exp'],
		'data_exp' => $date_conversor_exp,
		
		'CPF' => $form_state['values']['CPF'],
		'nacionalidade' => $form_state['values']['nacionalidade'],
		'profissao' => $form_state['values']['profissao'],
		'estado_civil' => $form_state['values']['estado_civil'],
		'tipo' => $form_state['values']['tipo'],
		'pessoa_tipo' => $form_state['values']['pessoa_tipo'],
		'observacao' => $form_state['values']['observacao'],
		'PIS' => $form_state['values']['PIS'],
		'num_ct' => $form_state['values']['num_ct'],
		'serie' => $form_state['values']['serie'],
		'res_endereco' => $form_state['values']['res_endereco'],
		//residencial
		'res_CEP' => $form_state['values']['res_CEP'],
		'res_estado' => $form_state['values']['res_estado'],
		'res_cidade' => $form_state['values']['res_cidade'],
		'res_telefone' => $form_state['values']['res_telefone'],
		'res_celular' => $form_state['values']['res_celular'],
		'res_email' => $form_state['values']['res_email'],
		//comercial
		'com_endereco' => $form_state['values']['com_endereco'],
		'com_CEP' => $form_state['values']['com_CEP'],
		'com_estado' => $form_state['values']['com_estado'],
		'com_cidade' => $form_state['values']['com_cidade'],
		'com_telefone' => $form_state['values']['com_telefone'],
		'com_celular' => $form_state['values']['com_celular'],
		'com_email' => $form_state['values']['com_email'],
	);
	
	drupal_write_record($table,$record);
	drupal_set_message('Inserido com sucesso','status');

	$output = "Inserido no banco com sucesso!";
	$output_error = "Erro na inserção";

	if(drupal_write_record($table,$record)){
		drupal_set_message('Inserido com sucesso','status');
		
		return "<div id='codigo-ajax'> $output </div>";
		}
	else{
		return "<div id='codigo-ajax'> $output_error </div>";
	}
 
	//$output = "Mensagem de exibição!";
	//$output = "Inserido no banco com sucesso!";
	//return "<div id='codigo-ajax'> $output </div>";

}

//regional
function form_regional_submit_callback($form, &$form_state) {
	$table = 'cadastros_regional';
	
	$record = array(
		'nome' => $form_state['values']['nome'],
	);


	$output = "Inserido no banco com sucesso!";
	$output_error = "Erro na inserção";
	
	if(drupal_write_record($table,$record)!=FALSE){
		//drupal_set_message('Inserido com sucesso','status');
		//$output = "Inserido no banco com sucesso!";
		$output = "CAIU NO IF";
		return "<div id='codigo-ajax'> $output </div>";
		}
	else{
		$output = "CAIU NO ELSE";
		return "<div id='codigo-ajax'> $output </div>";
	}
 
	//$output = "Mensagem de exibição!";
	//$output = "Inserido no banco com sucesso!";
	//return "<div id='codigo-ajax'> $output </div>";
}

//conta
function form_conta_submit_callback($form, &$form_state){
	$table = 'cadastros_conta';
	
	$record = array(
		'nome' => $form_state['values']['nome'],
	);
	
	$output = "Inserido no banco com sucesso!";
	$output_error = "Erro na inserção";
		
	
	if(drupal_write_record($table,$record)){
		drupal_set_message('Inserido com sucesso','status');
		return "<div id='codigo-ajax'> $output </div>";
		}
	else{
		return "<div id='codigo-ajax'> $output_error </div>";
	}
 
	//$output = "Mensagem de exibição!";
	//$output = "Inserido no banco com sucesso!";
	//return "<div id='codigo-ajax'> $output </div>";
}

//fase
function form_fase_submit_callback($form, &$form_state){
	$table = 'cadastros_fase';
	
	$record = array(
		'nome' => $form_state['values']['nome'],
	);
	
	if(drupal_write_record($table,$record)){
		drupal_set_message('Inserido com sucesso','status');
		$output = "Inserido no banco com sucesso!";
		return "<div id='codigo-ajax'> $output </div>";
		}
	else{
		return 0;
	}
 
	//$output = "Mensagem de exibição!";
	$output = "Inserido no banco com sucesso!";
	return "<div id='codigo-ajax'> $output </div>";
}

//exito
function form_exito_submit_callback($form, &$form_state){
	$table = 'cadastros_exito';
	
	$record = array(
		'nome' => $form_state['values']['nome'],
	);
	
	if(drupal_write_record($table,$record)) {
		drupal_set_message('Inserido com sucesso','status');
		$output = "Inserido no banco com sucesso!";
		return "<div id='codigo-ajax'> $output </div>";
	}
	else {
		return 0;
	}
 
	//$output = "Mensagem de exibição!";
	$output = "Inserido no banco com sucesso!";
	return "<div id='codigo-ajax'> $output </div>";
}

//recurso
function form_recursos_submit_callback($form, &$form_state){
	$table = 'cadastros_recursos';
	
	$record = array(
		'nome' => $form_state['values']['nome'],
	);
	
	if(drupal_write_record($table,$record)){
		drupal_set_message('Inserido com sucesso','status');
		$output = "Inserido no banco com sucesso!";
		return "<div id='codigo-ajax'> $output </div>";
		}
	else{
		return 0;
	}
 
	//$output = "Mensagem de exibição!";
	$output = "Inserido no banco com sucesso!";
	return "<div id='codigo-ajax'> $output </div>";
}

//ação
function form_acao_submit_callback($form, &$form_state){
	$table = 'cadastros_acao';
	
	$record = array(
		'nome' => $form_state['values']['nome'],
	);
	
	if(drupal_write_record($table,$record)){
		drupal_set_message('Inserido com sucesso','status');
		$output = "Inserido no banco com sucesso!";
		return "<div id='codigo-ajax'> $output </div>";
		}
	else{
		return 0;
	}
 
	//$output = "Mensagem de exibição!";
	//$output = "Inserido no banco com sucesso!";
	//return "<div id='codigo-ajax'> $output </div>";
}

//comarca
function form_comarca_submit_callback($form, &$form_state){
	$table = 'cadastros_comarcas';
	
	$record = array(
		'nome' => $form_state['values']['nome'],
	);
	
	if(drupal_write_record($table,$record)){
		drupal_set_message('Inserido com sucesso','status');
		$output = "Inserido no banco com sucesso!";
		return "<div id='codigo-ajax'> $output </div>";
		}
	else{
		return 0;
	}
 
	//$output = "Mensagem de exibição!";
	$output = "Inserido no banco com sucesso!";
	return "<div id='codigo-ajax'> $output </div>";
}

//natureza
function form_natureza_submit_callback($form, &$form_state){
	$table = 'cadastros_natureza';
	
	$record = array(
		'nome' => $form_state['values']['nome'],
	);
	
/*	if(drupal_write_record($table,$record)){
		drupal_set_message('Inserido com sucesso','status');
		$output = "Inserido no banco com sucesso!";
		return "<div id='codigo-ajax'> $output </div>";
		}
	else{
		return 0;
	}
 
	//$output = "Mensagem de exibição!";
	$output = "Inserido no banco com sucesso!";
	return "<div id='codigo-ajax'> $output </div>";
*/	
		
	$output = "Inserido no banco com sucesso!";
	$output_error = "Erro na inserção";
		
	
	if(drupal_write_record($table,$record)){
		drupal_set_message('Inserido com sucesso','status');
		return "<div id='codigo-ajax'> $output </div>";
		}
	else{
		return "<div id='codigo-ajax'> $output_error </div>";
	}
 
}

//tribunais
function form_tribunais_submit_callback($form, &$form_state){
	$table = 'cadastros_tribunal';
	
	$record = array(
		'nome' => $form_state['values']['nome'],
	);
	
	if(drupal_write_record($table,$record)){
		drupal_set_message('Inserido com sucesso','status');
		$output = "Inserido no banco com sucesso!";
		return "<div id='codigo-ajax'> $output </div>";
		}
	else{
		return 0;
	}
 
	//$output = "Mensagem de exibição!";
	$output = "Inserido no banco com sucesso!";
	return "<div id='codigo-ajax'> $output </div>";
}

//varas
function form_varas_submit_callback($form, &$form_state){
	$table = 'cadastros_varas';
	
	$record = array(
		'nome' => $form_state['values']['nome'],
	);
	
	if(drupal_write_record($table,$record)){
		drupal_set_message('Inserido com sucesso','status');
		$output = "Inserido no banco com sucesso!";
		return "<div id='codigo-ajax'> $output </div>";
		}
	else{
		return 0;
	}
 
	//$output = "Mensagem de exibição!";
	$output = "Inserido no banco com sucesso!";
	return "<div id='codigo-ajax'> $output </div>";
}

//teste
function meu_form_submit_callback($form, &$form_state){
	$table = 'cadastros_varas';
	
	$record = array(
		'nome' => $form_state['values']['nome'],
	);
	
	if(drupal_write_record($table,$record)){
		drupal_set_message('Inserido com sucesso','status');
		$output = "Inserido no banco com sucesso!";
		return "<div id='codigo-ajax'> $output </div>";
		}
	else{
		return 0;
	}
 
	//$output = "Mensagem de exibição!";
	$output = "Inserido no banco com sucesso!";
	return "<div id='codigo-ajax'> $output </div>";
}

/*  
function teste_menu() {


	$items = array();
	//cadastro de cliente
	
	$items['teste/cliente'] = array(
		'title' => 'Cadastro de Cliente',
		'description' => 'Cadastre aqui o cliente',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('_teste_cadastros_client'),
		'access arguments' => array('access content')
	);
	
	//cadastro de varas
	$items['teste/projetos'] = array(
		'title' => 'Cadastro de Projetos',
		'description' => 'Cadastre aqui os projetos',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('_teste_cadastros_projetos'),
		'access arguments' => array('access content')
	);
	
	return $items;
}



function _teste_cadastros_projetos(){
	$form = array();
	
	$form['nome'] = array(
		'#type' => 'textfield',
		'#title' => 'Nome do projeto',
		'#required' => true
	);
	
		$form['enviar'] = array(
		'#type' => 'submit',
		'#value' => 'Enviar',
		'#required' => true
	);
	
	return $form;
}




function _teste_cadastros_client() {
	$form = array();

	//******PRINCIPAL
	//Nascimento
	//RG - orgao expedidor
	//Data exp
	//CPF
	//nacionalidade
	//profissão - estado civil
	//definição do fieldset
	$form['principal'] = array(
		'#type' => 'fieldset',
		'#title' => 'PRINCIPAL',
		'#collapsible' => TRUE,
		'#collapsed' => FALSE,
	);

	$form['principal']['nome'] = array(
		'#type' => 'textfield',
		'#title' => 'Nome do Cliente',
		'#required' => true
	);
	
	$form['principal']['data_nasc'] = array(
		'#type' => 'date',
		'#title' => 'Nascimento',
		'#required' => true
	);

		
	//RG varia de estado para estado
	$form['principal']['RG'] = array(
		'#type' => 'textfield',
		'#title' => 'RG',
		'#required' => true
	);
	
	$form['principal']['org_exp'] = array(
		'#type' => 'textfield',
		'#title' => 'Órgão Expedidor',
		'#required' => true
	);

	$form['principal']['data_exp'] = array(
		'#type' => 'date',
		'#title' => 'Data expedição',
		'#required' => true
	);
	
	$form['principal']['CPF'] = array(
		'#type' => 'textfield',
		'#title' => 'CPF',
		'#required' => true
	);

	$form['principal']['nacionalidade'] = array(
		'#type' => 'textfield',
		'#title' => 'Nacionalidade',
		'#required' => true
	);

	$form['principal']['profissao'] = array(
		'#type' => 'textfield',
		'#title' => 'Profissão',
		'#required' => true
	);

	$form['principal']['estado_civil'] = array(
       '#type' => 'select',
       '#title' => t('Estado Civil'),
       '#options' => array(
			0 => t('Solteiro'),
			1 => t('Casado'),
			2 => t('Divorciado'),
			3 => t('Viúvo'),
			4 => t('União Estável'),			
		),
       '#default_value' => 0,
       //'#description' => t('Selecione o Estado Civil'),
   );

	//*******OUTROS
	//PIS
	//Numero da CT - Série
	$form['outros'] = array(
		'#type' => 'fieldset',
		'#title' => 'OUTROS',
		'#collapsible' => TRUE,
		'#collapsed' => TRUE,
	);
		
	$form['outros']['PIS'] = array(
		'#type' => 'textfield',
		'#title' => 'Profissão',
		'#required' => false
	);	
	
	$form['outros']['num_CT'] = array(
		'#type' => 'textfield',
		'#title' => 'Número da CT',
		'#required' => false
	);	
	
	$form['outros']['serie'] = array(
		'#type' => 'textfield',
		'#title' => 'Série',
		'#required' => false
	);	
	
	//*******RESIDENCIAL
	//Endereço - CEP
	//estado - cidade - bairro
	//telefone - contato
	//email
	$form['residencial'] = array(
		'#type' => 'fieldset',
		'#title' => 'RESIDENCIAL',
		'#collapsible' => TRUE,
		'#collapsed' => TRUE,
	);
	
	$form['residencial']['endereco'] = array(
		'#type' => 'textfield',
		'#title' => 'Endereço',
		'#required' => true
	);	

	$form['residencial']['CEP'] = array(
		'#type' => 'textfield',
		'#title' => 'CEP',
		'#required' => false
	);	
	
	$form['residencial']['estado'] = array(
		'#type' => 'textfield',
		'#title' => 'UF',
		'#required' => true
	);	
	
	$form['residencial']['cidade'] = array(
		'#type' => 'textfield',
		'#title' => 'Cidade',
		'#required' => false
	);	

	$form['residencial']['telefone'] = array(
		'#type' => 'textfield',
		'#title' => 'Telefone',
		'#required' => false
	);	
	
	$form['residencial']['contato'] = array(
		'#type' => 'textfield',
		'#title' => 'Contato',
		'#required' => false
	);	
	
	$form['residencial']['email'] = array(
		'#type' => 'textfield',
		'#title' => 'Email',
		'#required' => false
	);	
	

	
	
	$form['enviar'] = array(
		'#type' => 'submit',
		'#value' => 'Enviar',
		'#required' => true
	);
	
	return $form;
}

*/
