<?php
/**
* Implements hook_views_api().
*/
/*
function cadastros_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'cadastros') . '/views',
  );
*/

}


/**
* Implements hook_views_data().
*/
function cadastros_views_data() {
/*	
	$data['cadastros_clientes']['table']['group'] = t('Content');
	
	$data['cadastros_clientes']['table']['base'] = array(
		'field' => 'id',
		'title' => 'Tabela de Tipos de Ação',
		'weight' => -10,

	);

	$data['cadastros_clientes']['table']['join'] = array(
      'cadastros_acao' => array(
		'left_field' => 'id',
		'field' => 'id',
	  ),
      'cadastros_varas' => array(
		'left_field' => 'id',
		'field' => 'id',
	  ),
    );
  
  return $data;
 
*/
}
