<?php

function processos_form_alter(&$form, &$form_state, $form_id) {

}

function pr($array_or_object){
	echo '<pre>',print_r($array_or_object,1),'</pre>';
}

function search_codSap($filterCodSap){
	$result = db_result(db_query('SELECT * FROM {content_type_product} ctp WHERE ctp.field_codigo_value = %d',$filterCodSap));
	return array( 'result' => $result);
}

/**
  * Implements hook_permission().
  * Definições das permissões de uso e acesso ao módulo
  */
function processos_permission() {
	return array(
		'Liberar processos' => array(
		'title' => t('Access module processos'),
		'description' => t('Administração e acesso ao módulo.'),
		),
	);
}



/**
  * Implements hook_menu().
  */
function processos_menu() {
	$items = array();
	
	//cadastro de processos
	$items['juridico/processos'] = array(
		'title' => 'Processos',
		'description' => 'Cadastro de processos',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('processos_basico'),
		'access arguments' => array('Liberar processos'),
	);

	$items['juridico/listagem'] = array(
		'title' => 'Listagem',
		'description' => 'Listagem dos dados',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('listagem_basica'),
		'access arguments' => array('Liberar processos'),
	);
	
	//cadastro de processos
	$items['juridico/processos/processo_arquivado'] = array(
		'title' => 'Processo Arquivado',
		'description' => 'Cadastro de processos',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('_processos_cadastro_arquivado'),
		'access arguments' => array('Liberar processos'),
		'file' => 'processos.inc',
	);
	
	//cadastro de processos
	$items['juridico/processos/processo_corrente'] = array(
		'title' => 'Processo Corrente',
		'description' => 'Cadastro de processos',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('_processos_cadastro_corrente'),
		'access arguments' => array('Liberar processos'),
		'file' => 'processos.inc',
	);
	
	
	return $items;
}

function renderiza_cadastro($variable_type){
	
	switch ($variable_type) {
		case 0:
			$table = 'cadastros_acao';
			//drupal_set_message('Ação!','warning');
			break;
		case 1:
			$table = 'cadastros_comarcas';
			//drupal_set_message('Comarcas!','warning');
			break;
		case 2:
			$table = 'cadastros_conta';
			break;
	   case 3:
			$table = 'cadastros_exito';
			break;
	   case 4:
			$table = 'cadastros_fase';
			break;
	   case 5:
			$table = 'cadastros_natureza';
			break;
	   case 6:
			$table = 'cadastros_regional';
			break;
	   case 7:
			$table = 'cadastros_recursos';
			break;
	   case 8:
			$table = 'cadastros_tribunal';
			break;
	   case 9:
			$table = 'cadastros_varas';
			break;
	}

	$query = 'select cv.id, cv.nome from '.$table.' cv';
	$rows = db_query($query);
	
	
	//$output  = '<div id="main">';
    //$output = '<div id="post-content">';
	
	$output = '<table class="zebra_table">';
	//$output .= '<tr><td>id</td><td>Nome</td></tr>';
	
	foreach($rows as $rec => $value)
	{
		//visualizar a montagem do $new;
		$output .= '<tr><td>'.$value->id.'</td><td>'.$value->nome.'</td></tr>';
		//drupal_set_message(dpr(),'warning');
	}
	$output .= '</table>';
    //$output .= '</div>';
    //$output .= '</div>';
    
    return $output;
    //return $new;
	/*
	if($rows){
		$output = '<table class="table" id="lines-list"><tr>';
		$i = $colNumber = 1;
		//while ($row = db_fetch_object($rows)) :
		drupal_set_message(dpr($rows),'status');
		//	if (!$row->nid && !$row->children) continue;
	}			
	*/
	
}

function listagem_basica() {
	$form = array();
	//redirecionar pro node de escolha de processos
	//$act = renderiza_cadastro(9);
	$breadcrumb = array();
	$breadcrumb[] = l('Home',base_path());
	$breadcrumb[] = l('Juridico','juridico');
	//$breadcrumb[] = l('Processos',base_path().'processos');
	//$breadcrumb[] = l(drupal_get_title(),base_path() . request_uri());
	
	//$breadcrumb[] = l('Processo Corrente','processos/processo_corrente');
	drupal_set_breadcrumb($breadcrumb);
	return $form;
	//global $attributes_array;
	//drupal_set_message(dpr($page),'status');
	//print render($page['processos']);

}


function processos_basico() {
	$form = array();
	//redirecionar pro node de escolha de processos
	//$act = renderiza_cadastro(9);
	$breadcrumb = array();
	$breadcrumb[] = l('Home',base_path());
	$breadcrumb[] = l('Juridico','juridico');
	//$breadcrumb[] = l('Processos',base_path().'processos');
	//$breadcrumb[] = l(drupal_get_title(),base_path() . request_uri());
	
	//$breadcrumb[] = l('Processo Corrente','processos/processo_corrente');
	drupal_set_breadcrumb($breadcrumb);


	return $form;
	//global $attributes_array;
	//drupal_set_message(dpr($page),'status');
	//print render($page['processos']);

}

function _processos_cadastro_corrente() {
	//module_load_include('inc', 'popup', '/includes/popup.api');
	module_load_include('inc', 'popup', '/includes/popup.api');
	$form = array();
	
	//****Dados Processuais
	$form['processuais'] = array(
		'#type' => 'fieldset',
		'#title' => 'Dados Processuais',
		'#collapsible' => TRUE,
		'#collapsed' => FALSE,
	);
	
	$form['processuais']['nome'] = array(
		'#type' => 'textfield',
		'#title' => 'Processo',
		'#required' => true
	);
	
	$form['processuais']['inicio'] = array(
		'#type' => 'date',
		'#title' => 'Inicio',
		'#required' => true,
	);

	$form['processuais']['valor'] = array(
		'#type' => 'textfield',
		'#title' => 'Valor',
		'#required' => true
	);
	
	$form['processuais']['pasta'] = array(
		'#type' => 'textfield',
		'#title' => 'Pasta',
		'#required' => true
	);
	
	$form['processuais']['subpasta'] = array(
		'#type' => 'textfield',
		'#title' => 'Sub-Pasta',
		'#required' => true
	);
	
	$form['processuais']['regional'] = array(
       '#type' => 'select',
       '#title' => 'Regional',
       '#options' => returnDateCadastros(6),
       '#field_suffix' => popup(array('form' => 'form_regional', 'activate' => 'click','close' => TRUE, 'width' => 500)),
       //popup(array('form' => 'search_form', 'activate' => 'click', 'ajax' => 1, 'width' => 350))
       //'#default_value' => 0,
       //'#description' => t('Selecione o Estado Civil'),
    );
	
	$form['processuais']['natureza'] = array(
       '#type' => 'select',
       '#title' => 'Natureza',
       '#options' => returnDateCadastros(5),
       '#field_suffix' => popup(array('form' => 'form_natureza', 'activate' => 'click','close' => TRUE, 'width' => 500)),
       //'#default_value' => 0,
       //'#description' => t('Selecione o Estado Civil'),
   );
	
	$form['processuais']['acao'] = array(
       '#type' => 'select',
       '#title' => 'Ação',
       '#options' => returnDateCadastros(0),
       //'#default_value' => 0,
       //'#description' => t('Selecione o Estado Civil'),
   );

	$form['processuais']['fase'] = array(
       '#type' => 'select',
       '#title' => 'Fase',
       '#options' => returnDateCadastros(4),
       //'#default_value' => 0,
       //'#description' => t('Selecione o Estado Civil'),
    );

	$form['processuais']['comarca'] = array(
       '#type' => 'select',
       '#title' => 'Comarca',
       '#options' => returnDateCadastros(1),
       //'#default_value' => 0,
       //'#description' => t('Selecione o Estado Civil'),
    );
	
	$form['processuais']['vara'] = array(
       '#type' => 'select',
       '#title' => 'Vara',
       '#options' => returnDateCadastros(9),
       //'#default_value' => 0,
       //'#description' => t('Selecione o Estado Civil'),
    );
	
	$form['processuais']['exito'] = array(
       '#type' => 'select',
       '#title' => 'Êxito',
       '#options' => returnDateCadastros(3),
       //'#default_value' => 0,
       //'#description' => t('Selecione o Estado Civil'),
    );

	
	//****CLIENTE
	$form['cliente'] = array(
		'#type' => 'fieldset',
		'#title' => 'CLIENTE',
		'#collapsible' => TRUE,
		'#collapsed' => FALSE,
	);
	
	$form['cliente']['cliente_nome'] = array(
       '#type' => 'select',
       '#title' => 'Cliente',
       '#options' => returnDateCadastros(10),
		'#required' => true
       //'#default_value' => 0,
       //'#description' => t('Selecione o Estado Civil'),
    );

	$form['cliente']['cliente_parte'] = array(
		'#type' => 'textfield',
		'#title' => 'Parte',
		'#required' => true
	);

	$form['cliente']['cliente_advogado'] = array(
		'#type' => 'textfield',
		'#title' => 'Advogado',
		'#required' => true
	);
	
	//****ADVERSO
	$form['adverso'] = array(
		'#type' => 'fieldset',
		'#title' => 'ADVERSO',
		'#collapsible' => TRUE,
		'#collapsed' => FALSE,
	);
	
	$form['adverso']['adverso_nome'] = array(
		'#type' => 'textfield',
		'#title' => 'Adverso',
		'#required' => true
	);

	$form['adverso']['adverso_parte'] = array(
		'#type' => 'textfield',
		'#title' => 'Parte',
		'#required' => true
	);

	$form['adverso']['adverso_advogado'] = array(
		'#type' => 'textfield',
		'#title' => 'Advogado',
		'#required' => true
	);
	
	
	$form['enviar'] = array(
		'#type' => 'submit',
		'#value' => 'Enviar',
		'#required' => true
	);

	$form['#submit'][] = '_processos_correntes_settings_submit';
	
	$breadcrumb = array();
	$breadcrumb[] = l('Home',base_path());
	$breadcrumb[] = l('Juridico','juridico');
	$breadcrumb[] = l('Processos',base_path().'processos');
	//$breadcrumb[] = l(drupal_get_title(),base_path() . request_uri());
	
	//$breadcrumb[] = l('Processo Corrente','processos/processo_corrente');
	drupal_set_breadcrumb($breadcrumb);
	drupal_set_message(dpr($breadcrumb),'warning');
	return $form;


}

//********funções auxiliares
function returnDateCadastros($variable_type){
	switch ($variable_type) {
		case 0:
			$table = 'cadastros_acao';
			//drupal_set_message('Ação!','warning');
			break;
		case 1:
			$table = 'cadastros_comarcas';
			//drupal_set_message('Comarcas!','warning');
			break;
		case 2:
			$table = 'cadastros_conta';
			break;
	   case 3:
			$table = 'cadastros_exito';
			break;
	   case 4:
			$table = 'cadastros_fase';
			break;
	   case 5:
			$table = 'cadastros_natureza';
			break;
	   case 6:
			$table = 'cadastros_regional';
			break;
	   case 7:
			$table = 'cadastros_recursos';
			break;
	   case 8:
			$table = 'cadastros_tribunal';
			break;
	   case 9:
			$table = 'cadastros_varas';
			break;
	   case 10:
			$table = 'cadastros_clientes';
			break;
	
	}
	$result = db_query('select * from '.$table.'');

	//montando a option
	foreach($result as $rec => $value)
	{
		$new[$value->id] = $value->nome;
		//visualizar a montagem do $new;
		//drupal_set_message(dpr($new),'warning');
	}
    return $new;
}

//******* END funções auxiliares

function _processos_cadastro_arquivado() {
	$form = array();
	
	//****Dados Processuais
	$form['processuais'] = array(
		'#type' => 'fieldset',
		'#title' => 'Dados Processuais',
		'#collapsible' => TRUE,
		'#collapsed' => FALSE,
	);
	
	$form['processuais']['nome'] = array(
		'#type' => 'textfield',
		'#title' => 'Processo',
		'#required' => true
	);
	
	$form['processuais']['inicio'] = array(
		'#type' => 'date',
		'#title' => 'Inicio',
		'#required' => true
	);

	$form['processuais']['final'] = array(
		'#type' => 'date',
		'#title' => 'Arquivado em',
		'#required' => true
	);
	
	$form['processuais']['valor'] = array(
		'#type' => 'textfield',
		'#title' => 'Valor',
		'#required' => true
	);
	
	$form['processuais']['pasta'] = array(
		'#type' => 'textfield',
		'#title' => 'Pasta',
		'#required' => true
	);
	
	$form['processuais']['subpasta'] = array(
		'#type' => 'textfield',
		'#title' => 'Sub-Pasta',
		'#required' => true
	);
	
	$form['processuais']['regional'] = array(
       '#type' => 'select',
       '#title' => 'Regional',
       '#options' => returnDateCadastros(6),
       //'#default_value' => 0,
       //'#description' => t('Selecione o Estado Civil'),
    );
	
	$form['processuais']['natureza'] = array(
       '#type' => 'select',
       '#title' => 'Natureza',
       '#options' => returnDateCadastros(5),
       //'#default_value' => 0,
       //'#description' => t('Selecione o Estado Civil'),
   );
	
	$form['processuais']['acao'] = array(
       '#type' => 'select',
       '#title' => 'Ação',
       '#options' => returnDateCadastros(0),
       //'#default_value' => 0,
       //'#description' => t('Selecione o Estado Civil'),
   );

	$form['processuais']['fase'] = array(
       '#type' => 'select',
       '#title' => 'Fase',
       '#options' => returnDateCadastros(4),
       //'#default_value' => 0,
       //'#description' => t('Selecione o Estado Civil'),
    );

	$form['processuais']['comarca'] = array(
       '#type' => 'select',
       '#title' => 'Comarca',
       '#options' => returnDateCadastros(1),
       //'#default_value' => 0,
       //'#description' => t('Selecione o Estado Civil'),
    );
	
	$form['processuais']['vara'] = array(
       '#type' => 'select',
       '#title' => 'Vara',
       '#options' => returnDateCadastros(9),
       //'#default_value' => 0,
       //'#description' => t('Selecione o Estado Civil'),
    );
	
	$form['processuais']['exito'] = array(
       '#type' => 'select',
       '#title' => 'Êxito',
       '#options' => returnDateCadastros(3),
       //'#default_value' => 0,
       //'#description' => t('Selecione o Estado Civil'),
    );

	
	//****CLIENTE
	$form['cliente'] = array(
		'#type' => 'fieldset',
		'#title' => 'CLIENTE',
		'#collapsible' => TRUE,
		'#collapsed' => FALSE,
	);
	
	$form['cliente']['cliente_nome'] = array(
       '#type' => 'select',
       '#title' => 'Cliente',
       '#options' => returnDateCadastros(10),
		'#required' => true
       //'#default_value' => 0,
       //'#description' => t('Selecione o Estado Civil'),
    );

	$form['cliente']['cliente_parte'] = array(
		'#type' => 'textfield',
		'#title' => 'Parte',
		'#required' => true
	);

	$form['cliente']['cliente_advogado'] = array(
		'#type' => 'textfield',
		'#title' => 'Advogado',
		'#required' => true
	);
	
	//****ADVERSO
	$form['adverso'] = array(
		'#type' => 'fieldset',
		'#title' => 'ADVERSO',
		'#collapsible' => TRUE,
		'#collapsed' => FALSE,
	);
	
	$form['adverso']['adverso_nome'] = array(
		'#type' => 'textfield',
		'#title' => 'Adverso',
		'#required' => true
	);

	$form['adverso']['adverso_parte'] = array(
		'#type' => 'textfield',
		'#title' => 'Parte',
		'#required' => true
	);

	$form['adverso']['adverso_advogado'] = array(
		'#type' => 'textfield',
		'#title' => 'Advogado',
		'#required' => true
	);
	
	
	$form['enviar'] = array(
		'#type' => 'submit',
		'#value' => 'Enviar',
		'#required' => true
	);
	
	$form['#submit'][] = '_processos_arquivados_settings_submit';
	
	$breadcrumb = array();
	$breadcrumb[] = l('Home',base_path());
	$breadcrumb[] = l('Juridico','juridico');
	$breadcrumb[] = l('Processos',base_path().'processos');
	//$breadcrumb[] = l(drupal_get_title(),base_path() . request_uri());
	
	//$breadcrumb[] = l('Processo Corrente','processos/processo_corrente');
	drupal_set_breadcrumb($breadcrumb);
	
	
	return $form;
}

function processos_preprocess_page(&$variables){

//	drupal_set_message(dpr($variables['node']),'warning');
	
    //if(isset($variables['node']) && $variables['node']->your_field_name[LANGUAGE_NONE][0]['value']=='some_value') {
        $variables['theme_hook_suggestions'][] = 'page__processos__basico';
    //}
 //   	drupal_set_message(dpr($variables),'warning');
//    	print drupal_render($page['processos']);
}
